<?php



/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */

function custom_theme_theme_suggestions_node_alter(array &$suggestions, array $variables) {  //This hook allows you to alter the template suggestions for node rendering.
   if(\Drupal::currentUser()->isAnonymous()) {  //check if the user is anonymous
      $suggestions[] = "node__anonymous"; //This will suggest a new template suggestion for rendering a node when the user is anonymous.
   }
 }